# -*- coding: utf-8 -*-
"""parser.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gXmpB3KCZIlu3IuYjRefB6mhYnO1BgJ-
"""

import re

tsez_info = []
for_check = []

# ищет имя и название имя ищет до первой точки с пробелом за ней,
# название все что после этого до последовательности "точка пробел тире"
ref_name_title = '(^.+?\.) (.+?)\. –'
# дата отдельно, чтобы не падал поиск в тех строках где все хорошо но нет года
ref_date = '[^–\d](\d{4})[^–\d].*?$'

with open('tsez.txt', 'r', encoding='utf-8') as f:
  for line in f.readlines(): #читаем по строкам
    name_title =  re.search(ref_name_title, line) #ищем в строке имя и название
    if name_title: #если они есть записываем их в переменные
      name = name_title.group(1)
      title = name_title.group(2)
    else: # если нет то записываем индекс строки в список для проверки
      name_title = re.search('(^.+?\.) (.+?)//', line) # и теперь ищем название до двойного слеша и записываем данные
      name = name_title.group(1)
      title = name_title.group(2)
    if re.search(ref_date, line): #проверка, есть ли число похожее на год
      date = re.search(ref_date, line).group(1)
    else:
      date = '' # если нет то пустая строка
    tsez_info.append((name, title, date)) # записываем все три переменные в список с данными

import pandas as pd

df = pd.DataFrame(tsez_info, columns=['authors', 'title', 'date'])
df